from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(826, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_legend_title = QtWidgets.QLabel(self.centralwidget)
        self.label_legend_title.setGeometry(QtCore.QRect(650, 10, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_legend_title.setFont(font)
        self.label_legend_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_legend_title.setObjectName("label_legend_title")
        self.label_legend_text_air = QtWidgets.QLabel(self.centralwidget)
        self.label_legend_text_air.setGeometry(QtCore.QRect(650, 50, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_legend_text_air.setFont(font)
        self.label_legend_text_air.setAlignment(QtCore.Qt.AlignCenter)
        self.label_legend_text_air.setObjectName("label_legend_text_air")
        self.label_legend_image_air = QtWidgets.QLabel(self.centralwidget)
        self.label_legend_image_air.setGeometry(QtCore.QRect(650, 70, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_legend_image_air.setFont(font)
        self.label_legend_image_air.setText("")
        self.label_legend_image_air.setPixmap(QtGui.QPixmap("legend_components/air.png"))
        self.label_legend_image_air.setScaledContents(True)
        self.label_legend_image_air.setAlignment(QtCore.Qt.AlignCenter)
        self.label_legend_image_air.setObjectName("label_legend_image_air")
        self.label_legend_image_hydrogen = QtWidgets.QLabel(self.centralwidget)
        self.label_legend_image_hydrogen.setGeometry(QtCore.QRect(650, 120, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_legend_image_hydrogen.setFont(font)
        self.label_legend_image_hydrogen.setText("")
        self.label_legend_image_hydrogen.setPixmap(QtGui.QPixmap("legend_components/hydrogen.png"))
        self.label_legend_image_hydrogen.setScaledContents(True)
        self.label_legend_image_hydrogen.setAlignment(QtCore.Qt.AlignCenter)
        self.label_legend_image_hydrogen.setObjectName("label_legend_image_hydrogen")
        self.label_legend_text_hydrogen = QtWidgets.QLabel(self.centralwidget)
        self.label_legend_text_hydrogen.setGeometry(QtCore.QRect(650, 100, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_legend_text_hydrogen.setFont(font)
        self.label_legend_text_hydrogen.setAlignment(QtCore.Qt.AlignCenter)
        self.label_legend_text_hydrogen.setObjectName("label_legend_text_hydrogen")
        self.label_legend_image_oxygen = QtWidgets.QLabel(self.centralwidget)
        self.label_legend_image_oxygen.setGeometry(QtCore.QRect(650, 170, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_legend_image_oxygen.setFont(font)
        self.label_legend_image_oxygen.setText("")
        self.label_legend_image_oxygen.setPixmap(QtGui.QPixmap("legend_components/oxygen.png"))
        self.label_legend_image_oxygen.setScaledContents(True)
        self.label_legend_image_oxygen.setAlignment(QtCore.Qt.AlignCenter)
        self.label_legend_image_oxygen.setObjectName("label_legend_image_oxygen")
        self.label_legend_image_gen_gas = QtWidgets.QLabel(self.centralwidget)
        self.label_legend_image_gen_gas.setGeometry(QtCore.QRect(650, 220, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_legend_image_gen_gas.setFont(font)
        self.label_legend_image_gen_gas.setText("")
        self.label_legend_image_gen_gas.setPixmap(QtGui.QPixmap("legend_components/generator_gas.png"))
        self.label_legend_image_gen_gas.setScaledContents(True)
        self.label_legend_image_gen_gas.setAlignment(QtCore.Qt.AlignCenter)
        self.label_legend_image_gen_gas.setObjectName("label_legend_image_gen_gas")
        self.label_legend_text_gen_gas = QtWidgets.QLabel(self.centralwidget)
        self.label_legend_text_gen_gas.setGeometry(QtCore.QRect(650, 200, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_legend_text_gen_gas.setFont(font)
        self.label_legend_text_gen_gas.setAlignment(QtCore.Qt.AlignCenter)
        self.label_legend_text_gen_gas.setObjectName("label_legend_text_gen_gas")
        self.label_legend_text_oxygen = QtWidgets.QLabel(self.centralwidget)
        self.label_legend_text_oxygen.setGeometry(QtCore.QRect(650, 150, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_legend_text_oxygen.setFont(font)
        self.label_legend_text_oxygen.setAlignment(QtCore.Qt.AlignCenter)
        self.label_legend_text_oxygen.setObjectName("label_legend_text_oxygen")
        self.label_legend_image_helium = QtWidgets.QLabel(self.centralwidget)
        self.label_legend_image_helium.setGeometry(QtCore.QRect(650, 270, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_legend_image_helium.setFont(font)
        self.label_legend_image_helium.setText("")
        self.label_legend_image_helium.setPixmap(QtGui.QPixmap("legend_components/helium.png"))
        self.label_legend_image_helium.setScaledContents(True)
        self.label_legend_image_helium.setAlignment(QtCore.Qt.AlignCenter)
        self.label_legend_image_helium.setObjectName("label_legend_image_helium")
        self.label_legend_text_helium = QtWidgets.QLabel(self.centralwidget)
        self.label_legend_text_helium.setGeometry(QtCore.QRect(650, 250, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_legend_text_helium.setFont(font)
        self.label_legend_text_helium.setAlignment(QtCore.Qt.AlignCenter)
        self.label_legend_text_helium.setObjectName("label_legend_text_helium")
        self.label_image_outlines = QtWidgets.QLabel(self.centralwidget)
        self.label_image_outlines.setGeometry(QtCore.QRect(10, 10, 631, 411))
        self.label_image_outlines.setText("")
        self.label_image_outlines.setPixmap(QtGui.QPixmap("images/full/outlines.png"))
        self.label_image_outlines.setScaledContents(True)
        self.label_image_outlines.setObjectName("label_image_outlines")
        self.textBrowser_description = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_description.setGeometry(QtCore.QRect(10, 460, 631, 131))
        self.textBrowser_description.setObjectName("textBrowser_description")
        self.label_legend_title_description = QtWidgets.QLabel(self.centralwidget)
        self.label_legend_title_description.setGeometry(QtCore.QRect(10, 440, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_legend_title_description.setFont(font)
        self.label_legend_title_description.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_legend_title_description.setObjectName("label_legend_title_description")
        self.pushButton_full_scheme = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_full_scheme.setGeometry(QtCore.QRect(670, 562, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_full_scheme.setFont(font)
        self.pushButton_full_scheme.setObjectName("pushButton_full_scheme")
        self.radioButton_ground_launch = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_ground_launch.setGeometry(QtCore.QRect(650, 470, 171, 17))
        self.radioButton_ground_launch.setObjectName("radioButton_ground_launch")
        self.radioButton_ARM = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_ARM.setGeometry(QtCore.QRect(650, 490, 171, 17))
        self.radioButton_ARM.setObjectName("radioButton_ARM")
        self.radioButton_ARMtoRM = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_ARMtoRM.setGeometry(QtCore.QRect(650, 510, 171, 17))
        self.radioButton_ARMtoRM.setObjectName("radioButton_ARMtoRM")
        self.radioButton_RMtoARM = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_RMtoARM.setGeometry(QtCore.QRect(650, 530, 171, 17))
        self.radioButton_RMtoARM.setObjectName("radioButton_4")
        self.label_legend_title_modes = QtWidgets.QLabel(self.centralwidget)
        self.label_legend_title_modes.setGeometry(QtCore.QRect(650, 430, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_legend_title_modes.setFont(font)
        self.label_legend_title_modes.setAlignment(QtCore.Qt.AlignCenter)
        self.label_legend_title_modes.setObjectName("label_legend_title_modes")
        self.pushButton_backward = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_backward.setGeometry(QtCore.QRect(210, 430, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_backward.setFont(font)
        self.pushButton_backward.setObjectName("pushButton_backward")
        self.pushButton_forward = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_forward.setGeometry(QtCore.QRect(350, 430, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_forward.setFont(font)
        self.pushButton_forward.setObjectName("pushButton_forward")
        self.label_text_counter = QtWidgets.QLabel(self.centralwidget)
        self.label_text_counter.setGeometry(QtCore.QRect(600, 440, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_text_counter.setFont(font)
        self.label_text_counter.setObjectName("label_text_counter")
        self.label_image_overlay = QtWidgets.QLabel(self.centralwidget)
        self.label_image_overlay.setGeometry(QtCore.QRect(10, 10, 631, 411))
        self.label_image_overlay.setText("")
        self.label_image_overlay.setPixmap(QtGui.QPixmap(""))
        self.label_image_overlay.setScaledContents(True)
        self.label_image_overlay.setObjectName("label_image_overlay")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_legend_title.setText(_translate("MainWindow", "Легенда"))
        self.label_legend_text_air.setText(_translate("MainWindow", "Воздух"))
        self.label_legend_text_hydrogen.setText(_translate("MainWindow", "Водород"))
        self.label_legend_text_gen_gas.setText(_translate("MainWindow", "Генераторный газ"))
        self.label_legend_text_oxygen.setText(_translate("MainWindow", "Кислород"))
        self.label_legend_text_helium.setText(_translate("MainWindow", "Гелий"))
        self.label_legend_title_description.setText(_translate("MainWindow", "Описание "))
        self.pushButton_full_scheme.setText(_translate("MainWindow", "Полная схема"))
        self.radioButton_ground_launch.setText(_translate("MainWindow", "Наземный запуск двигателя"))
        self.radioButton_ARM.setText(_translate("MainWindow", "Воздушно-реактивный режим"))
        self.radioButton_ARMtoRM.setText(_translate("MainWindow", "Из ВРР в раккетный режим"))
        self.radioButton_RMtoARM.setText(_translate("MainWindow", "Из ракетного режима в ВРР"))
        self.label_legend_title_modes.setText(_translate("MainWindow", "Режимы"))
        self.pushButton_backward.setText(_translate("MainWindow", "Назад"))
        self.pushButton_forward.setText(_translate("MainWindow", "Вперед"))
        self.label_text_counter.setText(_translate("MainWindow", ""))
